<script lang="ts">
	import TableHeadItem from '$lib/tables/TableHeadItem.svelte';
	import TableDataCell from '$lib/tables/TableDataCell.svelte';
	import HopsNav from '$lib/nav/HopsNav.svelte';
	import type { PageData } from './$types';
	import Loading from '$lib/components/Loading.svelte';
	import type { EventTable } from '$lib/events/api';
	import { goto } from '$app/navigation';
	import HelperText from '$lib/components/HelperText.svelte';

	export let data: PageData;

	// Event logs table data
	$: tableData = data.tableData;
	$: ago = data.ago;
	$: loading = data.tableData === undefined;
	$: tab = data.tab;

	$: activeRow = tableData?.[0];

	function setActiveRow(row: EventTable) {
		activeRow = row;
	}

	const sourceHelperText =
		'<strong>Recent source events:</strong> Generated by apps, tasks and schedules when a pipeline runs';

	const allHelperText =
		'<strong>All recent events:</strong> Includes source events + other events that occur when a source event is generated';
</script>

<svelte:head>
	<title>Events</title>
	<meta name="description" content="Trigger task flows" />
</svelte:head>

{#if loading}
	<Loading />
{:else}
	<div class="dark:bg-grain bg-cover bg-norepeat bg-fixed min-h-screen">
		<HopsNav />

		<!--Page title-->
		<div class="md:pl-20 md:pr-20 mx-8 md:mx-auto mt-12">
			<h1 class="text-left text-5xl font-normal mb-1 dark:text-white">Events</h1>
		</div>

		<!-- Container-->

		<!--Helper text-->
		<div class="mx-8 mb-4 md:mx-20 rounded-lg justify-between flex items-center">
			{#if tab === 'Events'}
				<HelperText text={sourceHelperText} />
			{:else}
				<HelperText text={allHelperText} />
			{/if}

			<!--Tabs-->
			<div>
				<ul class="flex space-x-2">
					<li>
						<button
							on:click={() => goto('/console/events')}
							class={tab === 'Events'
								? 'bg-white text-black px-6 py-2 border border-black rounded-full font-semibold'
								: 'text-white border border-white rounded-full px-6 py-2 font-medium'}
							>Source
						</button>
					</li>
					<li>
						<button
							on:click={() => goto('/console/events?all=true')}
							class={tab === 'All'
								? 'bg-white text-black px-6 py-2 border border-black rounded-full font-semibold'
								: 'text-white border border-white rounded-full px-6 py-2 font-medium'}
							>All
						</button>
					</li>
				</ul>
			</div>
		</div>

		<!--Tasks empty state -->
		{#if tableData.length == 0}
			<div class="mx-8 md:mx-20 pb-20 md:space-x-4">
				<div
					class="bg-almostblack flex items-center justify-center text-center rounded-lg mt-4 py-60 md:!ml-0"
				>
					<p class="text-white text-base font-medium">No events since {ago}</p>
				</div>
			</div>
		{:else}
			<div class="flex space-x-4 pl-8 pr-8 md:pl-20 md:pr-20 text-white">
				<!--Events table container-->
				<div
					class="w-1/2 dark:bg-[#191919] dark:border-none border border-lightrey overflow-scroll h-[60vh] rounded-lg"
				>
					<div class="w-full">
						<table class="table-auto w-full">
							<thead class="text-left">
								<tr>
									<TableHeadItem>Timestamp</TableHeadItem>
									<TableHeadItem>ID</TableHeadItem>
									<TableHeadItem>Source</TableHeadItem>
									<TableHeadItem>Event</TableHeadItem>
									<TableHeadItem>Action</TableHeadItem>
								</tr>
							</thead>
							<tbody>
								{#each tableData as row, i (`${i}-${row.timestamp}`)}
									<tr
										class="hover:bg-lightgrey dark:hover:bg-almostblack {row === activeRow
											? 'border-l-2 border-purple bg-lightgrey dark:bg-almostblack'
											: ''}"
										on:click={() => setActiveRow(row)}
									>
										<TableDataCell>{row.timestamp}</TableDataCell>
										<TableDataCell>{row.eventId.slice(0, 7) + '...'}</TableDataCell>
										<TableDataCell>{row.source}</TableDataCell>
										<TableDataCell>{row.event}</TableDataCell>
										<TableDataCell>{row.action}</TableDataCell>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</div>

				<!--Selected event detail container-->
				{#if activeRow}
					<div
						class="w-1/2 bg-white border border-lightrey dark:border-purple dark:bg-[#191919] overflow-scroll h-[60vh] text-black dark:text-white rounded-lg"
					>
						<div class="p-8">
							<h2 class="text-xl mb-8 text-grey dark:text-midgrey">ID: {activeRow.eventId}</h2>
							<!--Pipelines container-->

							<div class="mt-4 mb-12">
								<div
									class="mt-4 mb-12 border-midgrey dark:border-almostblack py-1 text-sm text-grey dark:text-midgrey"
								>
									<pre>{JSON.stringify(activeRow.JSON, null, 2)}</pre>
								</div>
							</div>
						</div>
					</div>
				{/if}
			</div>
		{/if}
	</div>
{/if}
