version: "3.8"
services:
  hops:
    image: ko.local/hops-c37ae648861240e86430fc7296dbed6d
    platform: "linux/arm64"
    ports:
      - 4222:4222
    environment:
      HIPHOPS_TAG: "dev"
      HIPHOPS_DIR: "/hiphops/"
      HIPHOPS_RUNNER_DATA_DIR: "/hiphops/.hiphops/data/jetstream"
    volumes:
      - type: bind
        source: .
        target: /hiphops/

  user-app:
    image: user-app:v1
