apiVersion: v1
kind: Service
metadata:
  name: hops
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.hiphops.hostPort | default 8196 }}
      targetPort: 8916
      protocol: TCP
  selector:
    app: hops
