version: "3.8"
services:
  hops:
    image: hiphops/hiphops:alpha-2408-oriented-labrador
    platform: "linux/arm64"
    ports:
      - 4222:4222
    healthcheck:
      test: ["CMD", "hiphops", "health"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    environment:
      HIPHOPS_TAG: "dev"
      HIPHOPS_DIR: "/hiphops/"
      HIPHOPS_RUNNER_DATA_DIR: "/hiphops/.hiphops/data/"
    volumes:
      - type: bind
        source: .
        target: /hiphops/

  runtime:
    image: hiphops/runtime-deno:alpha-2408-lonely-kouprey
    depends_on:
      hops:
        condition: service_healthy
    ports:
      - 8080:8080
    entrypoint: "sh"
    command: ["/hiphops/watch.sh"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://127.0.0.1:8080/health"]
      interval: 5s
      retries: 5
      start_period: 1s
      timeout: 5s
    volumes:
      - type: bind
        source: ./flows
        target: /hiphops/flows
      - type: bind
        source: ./.hiphops/watch.sh
        target: /hiphops/watch.sh
      - type: bind
        source: ./.hiphops/site
        target: /hiphops/site
